
channels:
  - conda-forge
  - defaults
dependencies:
  # Include requirements for the docs
  - sphinx>=2.2
  - sphinxcontrib-bibtex
  - sphinx-book-theme>=1.0.1
  - sphinx-design
  - ipython>=6.3.1
  - ruamel.yaml
  - psutil
  - numpy
  - jax
  - jaxlib
